# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xci
# IP: The module: 'zynq_bd_C2C1_PHY_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] -quiet

# IP: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/zynq_bd_C2C1_PHY_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_gt || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_gt} -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt_ooc.xdc

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_gt || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xci
# IP: The module: 'zynq_bd_C2C1_PHY_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] -quiet

# IP: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/zynq_bd_C2C1_PHY_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_gt || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_gt} -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_fifo_gen_master} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt_ooc.xdc

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0_gt || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_C2C1_PHY_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
