# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/onboardclk/onboardclk.xci
# IP: The module: 'onboardclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: ip/onboardclk/onboardclk.xci
# IP: The module: 'onboardclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'onboardclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
