# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/top.xdc

# XDC: imports/src/top_clocks.xdc

# XDC: imports/src/top_MGMT.xdc

# Block Designs: bd/zynq_bd/zynq_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd || ORIG_REF_NAME==zynq_bd} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_ZynqMPSoC_0/zynq_bd_ZynqMPSoC_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_ZynqMPSoC_0 || ORIG_REF_NAME==zynq_bd_ZynqMPSoC_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_sys_resetter_primary_0/zynq_bd_sys_resetter_primary_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_sys_resetter_primary_0 || ORIG_REF_NAME==zynq_bd_sys_resetter_primary_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_sys_resetter_primary_BUS_RST_N_0/zynq_bd_sys_resetter_primary_BUS_RST_N_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_sys_resetter_primary_BUS_RST_N_0 || ORIG_REF_NAME==zynq_bd_sys_resetter_primary_BUS_RST_N_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_sys_resetter_c2c_0/zynq_bd_sys_resetter_c2c_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_sys_resetter_c2c_0 || ORIG_REF_NAME==zynq_bd_sys_resetter_c2c_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_sys_resetter_c2c_BUS_RST_N_0/zynq_bd_sys_resetter_c2c_BUS_RST_N_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_sys_resetter_c2c_BUS_RST_N_0 || ORIG_REF_NAME==zynq_bd_sys_resetter_c2c_BUS_RST_N_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_SYS_RESET_0/zynq_bd_SYS_RESET_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_SYS_RESET_0 || ORIG_REF_NAME==zynq_bd_SYS_RESET_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_SYS_RESET_BUS_RST_N_0/zynq_bd_SYS_RESET_BUS_RST_N_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_SYS_RESET_BUS_RST_N_0 || ORIG_REF_NAME==zynq_bd_SYS_RESET_BUS_RST_N_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_xbar_0/zynq_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_xbar_0 || ORIG_REF_NAME==zynq_bd_xbar_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_14/zynq_bd_auto_pc_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_14 || ORIG_REF_NAME==zynq_bd_auto_pc_14} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_0/zynq_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_0 || ORIG_REF_NAME==zynq_bd_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_1/zynq_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_1 || ORIG_REF_NAME==zynq_bd_auto_pc_1} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_2/zynq_bd_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_2 || ORIG_REF_NAME==zynq_bd_auto_pc_2} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_3/zynq_bd_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_3 || ORIG_REF_NAME==zynq_bd_auto_pc_3} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_4/zynq_bd_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_4 || ORIG_REF_NAME==zynq_bd_auto_pc_4} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_5/zynq_bd_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_5 || ORIG_REF_NAME==zynq_bd_auto_pc_5} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_6/zynq_bd_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_6 || ORIG_REF_NAME==zynq_bd_auto_pc_6} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_7/zynq_bd_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_7 || ORIG_REF_NAME==zynq_bd_auto_pc_7} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_8/zynq_bd_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_8 || ORIG_REF_NAME==zynq_bd_auto_pc_8} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_9/zynq_bd_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_9 || ORIG_REF_NAME==zynq_bd_auto_pc_9} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_10/zynq_bd_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_10 || ORIG_REF_NAME==zynq_bd_auto_pc_10} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_11/zynq_bd_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_11 || ORIG_REF_NAME==zynq_bd_auto_pc_11} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_12/zynq_bd_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_12 || ORIG_REF_NAME==zynq_bd_auto_pc_12} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_13/zynq_bd_auto_pc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_13 || ORIG_REF_NAME==zynq_bd_auto_pc_13} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_AXI_MAIN_INTERCONNECT_0/zynq_bd_AXI_MAIN_INTERCONNECT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_AXI_MAIN_INTERCONNECT_0 || ORIG_REF_NAME==zynq_bd_AXI_MAIN_INTERCONNECT_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_xbar_1/zynq_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_xbar_1 || ORIG_REF_NAME==zynq_bd_xbar_1} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_15/zynq_bd_auto_pc_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_15 || ORIG_REF_NAME==zynq_bd_auto_pc_15} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_16/zynq_bd_auto_pc_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_16 || ORIG_REF_NAME==zynq_bd_auto_pc_16} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_17/zynq_bd_auto_pc_17.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_17 || ORIG_REF_NAME==zynq_bd_auto_pc_17} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_18/zynq_bd_auto_pc_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_18 || ORIG_REF_NAME==zynq_bd_auto_pc_18} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_19/zynq_bd_auto_pc_19.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_19 || ORIG_REF_NAME==zynq_bd_auto_pc_19} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_20/zynq_bd_auto_pc_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_20 || ORIG_REF_NAME==zynq_bd_auto_pc_20} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_21/zynq_bd_auto_pc_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_21 || ORIG_REF_NAME==zynq_bd_auto_pc_21} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_AXI_C2C_INTERCONNECT_0/zynq_bd_AXI_C2C_INTERCONNECT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_AXI_C2C_INTERCONNECT_0 || ORIG_REF_NAME==zynq_bd_AXI_C2C_INTERCONNECT_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_IRQ0_INTR_CTRL_0/zynq_bd_IRQ0_INTR_CTRL_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_IRQ0_INTR_CTRL_0 || ORIG_REF_NAME==zynq_bd_IRQ0_INTR_CTRL_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_IRQ0_INTR_CTRL_IRQ_0/zynq_bd_IRQ0_INTR_CTRL_IRQ_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_IRQ0_INTR_CTRL_IRQ_0 || ORIG_REF_NAME==zynq_bd_IRQ0_INTR_CTRL_IRQ_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1_0/zynq_bd_C2C1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_0 || ORIG_REF_NAME==zynq_bd_C2C1_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_PHY_0 || ORIG_REF_NAME==zynq_bd_C2C1_PHY_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1_AXI_FW_0/zynq_bd_C2C1_AXI_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_AXI_FW_0 || ORIG_REF_NAME==zynq_bd_C2C1_AXI_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1B_0/zynq_bd_C2C1B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1B_0 || ORIG_REF_NAME==zynq_bd_C2C1B_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/zynq_bd_C2C1B_PHY_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1B_PHY_0 || ORIG_REF_NAME==zynq_bd_C2C1B_PHY_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C1_AXILITE_FW_0/zynq_bd_C2C1_AXILITE_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C1_AXILITE_FW_0 || ORIG_REF_NAME==zynq_bd_C2C1_AXILITE_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2_0/zynq_bd_C2C2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2_0 || ORIG_REF_NAME==zynq_bd_C2C2_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/zynq_bd_C2C2_PHY_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2_PHY_0 || ORIG_REF_NAME==zynq_bd_C2C2_PHY_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2_AXI_FW_0/zynq_bd_C2C2_AXI_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2_AXI_FW_0 || ORIG_REF_NAME==zynq_bd_C2C2_AXI_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2B_0/zynq_bd_C2C2B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2B_0 || ORIG_REF_NAME==zynq_bd_C2C2B_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/zynq_bd_C2C2B_PHY_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2B_PHY_0 || ORIG_REF_NAME==zynq_bd_C2C2B_PHY_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_C2C2_AXILITE_FW_0/zynq_bd_C2C2_AXILITE_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_C2C2_AXILITE_FW_0 || ORIG_REF_NAME==zynq_bd_C2C2_AXILITE_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_xbar_2/zynq_bd_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_xbar_2 || ORIG_REF_NAME==zynq_bd_xbar_2} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_22/zynq_bd_auto_pc_22.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_22 || ORIG_REF_NAME==zynq_bd_auto_pc_22} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_23/zynq_bd_auto_pc_23.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_23 || ORIG_REF_NAME==zynq_bd_auto_pc_23} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_24/zynq_bd_auto_pc_24.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_24 || ORIG_REF_NAME==zynq_bd_auto_pc_24} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_AXI_LOCAL_INTERCONNECT_0/zynq_bd_AXI_LOCAL_INTERCONNECT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_AXI_LOCAL_INTERCONNECT_0 || ORIG_REF_NAME==zynq_bd_AXI_LOCAL_INTERCONNECT_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_PL_MEM_0/zynq_bd_PL_MEM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_PL_MEM_0 || ORIG_REF_NAME==zynq_bd_PL_MEM_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_PL_MEM_RAM_0/zynq_bd_PL_MEM_RAM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_PL_MEM_RAM_0 || ORIG_REF_NAME==zynq_bd_PL_MEM_RAM_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_PL_MEM_CM_0/zynq_bd_PL_MEM_CM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_PL_MEM_CM_0 || ORIG_REF_NAME==zynq_bd_PL_MEM_CM_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_PL_MEM_CM_RAM_0/zynq_bd_PL_MEM_CM_RAM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_PL_MEM_CM_RAM_0 || ORIG_REF_NAME==zynq_bd_PL_MEM_CM_RAM_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_CM_MON_AXI_FW_0/zynq_bd_CM_MON_AXI_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_CM_MON_AXI_FW_0 || ORIG_REF_NAME==zynq_bd_CM_MON_AXI_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_MONITOR_0/zynq_bd_MONITOR_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_MONITOR_0 || ORIG_REF_NAME==zynq_bd_MONITOR_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_SI_0 || ORIG_REF_NAME==zynq_bd_SI_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_CM1_UART_0/zynq_bd_CM1_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_CM1_UART_0 || ORIG_REF_NAME==zynq_bd_CM1_UART_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_CM2_UART_0/zynq_bd_CM2_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_CM2_UART_0 || ORIG_REF_NAME==zynq_bd_CM2_UART_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_CM1_PB_UART_0/zynq_bd_CM1_PB_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_CM1_PB_UART_0 || ORIG_REF_NAME==zynq_bd_CM1_PB_UART_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_CM2_PB_UART_0/zynq_bd_CM2_PB_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_CM2_PB_UART_0 || ORIG_REF_NAME==zynq_bd_CM2_PB_UART_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_ESM_UART_0/zynq_bd_ESM_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_ESM_UART_0 || ORIG_REF_NAME==zynq_bd_ESM_UART_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_AXI_MON_0/zynq_bd_AXI_MON_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_AXI_MON_0 || ORIG_REF_NAME==zynq_bd_AXI_MON_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_INT_AXI_FW_0/zynq_bd_INT_AXI_FW_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_INT_AXI_FW_0 || ORIG_REF_NAME==zynq_bd_INT_AXI_FW_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axis_data_fifo_0_0/zynq_bd_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axis_data_fifo_0_0 || ORIG_REF_NAME==zynq_bd_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axi_dma_0_0/zynq_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axi_dma_0_0 || ORIG_REF_NAME==zynq_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_xlconstant_0_0/zynq_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_xlconstant_0_0 || ORIG_REF_NAME==zynq_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axis_jtag_0_0/zynq_bd_axis_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axis_jtag_0_0 || ORIG_REF_NAME==zynq_bd_axis_jtag_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_xbar_3/zynq_bd_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_xbar_3 || ORIG_REF_NAME==zynq_bd_xbar_3} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_us_0/zynq_bd_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_us_0 || ORIG_REF_NAME==zynq_bd_auto_us_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_us_1/zynq_bd_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_us_1 || ORIG_REF_NAME==zynq_bd_auto_us_1} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_us_2/zynq_bd_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_us_2 || ORIG_REF_NAME==zynq_bd_auto_us_2} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axi_interconnect_0_0/zynq_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axi_dma_0_1/zynq_bd_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axi_dma_0_1 || ORIG_REF_NAME==zynq_bd_axi_dma_0_1} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_axis_data_fifo_0_1/zynq_bd_axis_data_fifo_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_axis_data_fifo_0_1 || ORIG_REF_NAME==zynq_bd_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/zynq_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_smartconnect_0_0 || ORIG_REF_NAME==zynq_bd_smartconnect_0_0} -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/zynq_bd_ooc.xdc
