# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -string {{.*The IP file '.*' has been moved from its original location, as a result the outputs for this IP will now be generated in '.*'. Alternatively a copy of the IP can be imported into the project using one of the 'import_ip' or 'import_files' commands..*}}  -suppress  -regexp
set_msg_config  -string {{.*File '.*.xci' referenced by design '.*' could not be found..*}}  -suppress  -regexp
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-fbvb900-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.cache/wt [current_project]
set_property parent.project_path C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Dev/apollo_sm_vivado/ip_repo/axis_jtag [current_project]
update_ip_catalog
set_property ip_output_repo c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {GLOBAL_DATE=32'h02122023 GLOBAL_TIME=32'h00173554 GLOBAL_VER=32'h01090001 GLOBAL_SHA=32'h019518AA TOP_SHA=32'h073D7DC1 TOP_VER=32'h01070000 HOG_SHA=32'h014E310A HOG_VER=32'h070A0000 CON_VER=32'h01040005 CON_SHA=32'h0A11F093 XML_VER=32'h00000000 XML_SHA=32'h00000000 XIL_DEFAULTLIB_VER=32'h01090001 XIL_DEFAULTLIB_SHA=32'h019518AA} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/new/jtag_mux.sv
read_vhdl -library xil_defaultlib {
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/AXI_slave_pkg.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/CM/CM_PKG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/CM/CM_map.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/Global_PKG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/PLXVC/PLXVC_PKG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/PLXVC/PLXVC_map.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/SERV/SERV_PKG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/SERV/SERV_map.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/SM_INFO/SM_INFO_PKG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/autogen/SM_INFO/SM_INFO_map.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/apollo_sm_vivado/rev2a_xczu7ev/zynq_bd/hdl/zynq_bd_sane_wrapper.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/types.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiRegWidthPkg_32.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiRegPkg.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/bramPortPkg.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiRegBlocking.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiReg.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiRegPkg_d64.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/Button_Debouncer.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/Button_Decoder.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/regmap_helper/axiReg/axiRegMaster.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/picoblaze/uart_rx6.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/uart_rx6.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/counter.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/CM_Monitoring/CM_Monitoring.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/CM_package.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/picoblaze/picoblaze/cli.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/picoblaze/uC.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/CM_pwr.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/DC_data_CDC.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/pacd.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/data_CDC.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/capture_CDC.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/rate_counter.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/counter_CDC.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/CM_interface.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/services/CPLD_INFO/CPLD_INFO.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/LED_Encoder.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/FrontPanel_UI.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/IPMC_i2c_slave/i2c_slave.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/asym_dualport_ram.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/IPMC_i2c_slave/IPMC_i2c_slave.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/LED_Paterns.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/misc/XILINX_DNA.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/SM_info/SM_info.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/front_panel/SR_Out.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/picoblaze/picoblaze/kcpsm6.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/plXVC/virtualJTAG.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/plXVC/plXVC_intf.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/register_pkg.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/services/services_rev2.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/src/CM_interface/picoblaze/uart_tx6.vhd
  C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/imports/apollo/SM_ZYNQ_FW/configs/rev2a_xczu7ev/src/top.vhd
}
add_files C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/bd/zynq_bd/zynq_bd.bd
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ZynqMPSoC_0/zynq_bd_ZynqMPSoC_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ZynqMPSoC_0/zynq_bd_ZynqMPSoC_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_primary_0/zynq_bd_sys_resetter_primary_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_primary_0/zynq_bd_sys_resetter_primary_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_primary_0/zynq_bd_sys_resetter_primary_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_c2c_0/zynq_bd_sys_resetter_c2c_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_c2c_0/zynq_bd_sys_resetter_c2c_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_sys_resetter_c2c_0/zynq_bd_sys_resetter_c2c_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SYS_RESET_0/zynq_bd_SYS_RESET_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SYS_RESET_0/zynq_bd_SYS_RESET_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SYS_RESET_0/zynq_bd_SYS_RESET_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_xbar_0/zynq_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_14/zynq_bd_auto_pc_14_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_0/zynq_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_1/zynq_bd_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_2/zynq_bd_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_3/zynq_bd_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_4/zynq_bd_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_5/zynq_bd_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_6/zynq_bd_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_7/zynq_bd_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_8/zynq_bd_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_9/zynq_bd_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_10/zynq_bd_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_11/zynq_bd_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_12/zynq_bd_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_13/zynq_bd_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_xbar_1/zynq_bd_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_15/zynq_bd_auto_pc_15_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_16/zynq_bd_auto_pc_16_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_17/zynq_bd_auto_pc_17_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_18/zynq_bd_auto_pc_18_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_19/zynq_bd_auto_pc_19_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_20/zynq_bd_auto_pc_20_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_21/zynq_bd_auto_pc_21_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_IRQ0_INTR_CTRL_0/zynq_bd_IRQ0_INTR_CTRL_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_IRQ0_INTR_CTRL_0/zynq_bd_IRQ0_INTR_CTRL_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_IRQ0_INTR_CTRL_0/zynq_bd_IRQ0_INTR_CTRL_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_0/zynq_bd_C2C1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_0/zynq_bd_C2C1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_0/zynq_bd_C2C1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_1/zynq_bd_C2C1_PHY_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/ip_0/synth/zynq_bd_C2C1_PHY_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_waivers.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_PHY_0/zynq_bd_C2C1_PHY_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_AXI_FW_0/zynq_bd_C2C1_AXI_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_0/zynq_bd_C2C1B_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_0/zynq_bd_C2C1B_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_0/zynq_bd_C2C1B_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/ip_1/zynq_bd_C2C1B_PHY_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/ip_1/zynq_bd_C2C1B_PHY_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/ip_0/synth/zynq_bd_C2C1B_PHY_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/ip_0/synth/zynq_bd_C2C1B_PHY_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/zynq_bd_C2C1B_PHY_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/zynq_bd_C2C1B_PHY_0_waivers.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/zynq_bd_C2C1B_PHY_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1B_PHY_0/zynq_bd_C2C1B_PHY_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C1_AXILITE_FW_0/zynq_bd_C2C1_AXILITE_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_0/zynq_bd_C2C2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_0/zynq_bd_C2C2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_0/zynq_bd_C2C2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/ip_1/zynq_bd_C2C2_PHY_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/ip_1/zynq_bd_C2C2_PHY_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/ip_0/synth/zynq_bd_C2C2_PHY_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/ip_0/synth/zynq_bd_C2C2_PHY_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/zynq_bd_C2C2_PHY_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/zynq_bd_C2C2_PHY_0_waivers.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/zynq_bd_C2C2_PHY_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_PHY_0/zynq_bd_C2C2_PHY_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_AXI_FW_0/zynq_bd_C2C2_AXI_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_0/zynq_bd_C2C2B_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_0/zynq_bd_C2C2B_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_0/zynq_bd_C2C2B_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/ip_1/zynq_bd_C2C2B_PHY_0_fifo_gen_master.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/ip_1/zynq_bd_C2C2B_PHY_0_fifo_gen_master_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/ip_0/synth/zynq_bd_C2C2B_PHY_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/ip_0/synth/zynq_bd_C2C2B_PHY_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/zynq_bd_C2C2B_PHY_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/zynq_bd_C2C2B_PHY_0_waivers.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/zynq_bd_C2C2B_PHY_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2B_PHY_0/zynq_bd_C2C2B_PHY_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_C2C2_AXILITE_FW_0/zynq_bd_C2C2_AXILITE_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_xbar_2/zynq_bd_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_22/zynq_bd_auto_pc_22_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_23/zynq_bd_auto_pc_23_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_pc_24/zynq_bd_auto_pc_24_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_PL_MEM_0/zynq_bd_PL_MEM_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_PL_MEM_RAM_0/zynq_bd_PL_MEM_RAM_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_PL_MEM_CM_0/zynq_bd_PL_MEM_CM_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_PL_MEM_CM_RAM_0/zynq_bd_PL_MEM_CM_RAM_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM_MON_AXI_FW_0/zynq_bd_CM_MON_AXI_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_MONITOR_0/zynq_bd_MONITOR_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_MONITOR_0/zynq_bd_MONITOR_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_MONITOR_0/zynq_bd_MONITOR_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_UART_0/zynq_bd_CM1_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_UART_0/zynq_bd_CM1_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_UART_0/zynq_bd_CM1_UART_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_UART_0/zynq_bd_CM2_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_UART_0/zynq_bd_CM2_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_UART_0/zynq_bd_CM2_UART_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_PB_UART_0/zynq_bd_CM1_PB_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_PB_UART_0/zynq_bd_CM1_PB_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM1_PB_UART_0/zynq_bd_CM1_PB_UART_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_PB_UART_0/zynq_bd_CM2_PB_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_PB_UART_0/zynq_bd_CM2_PB_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_CM2_PB_UART_0/zynq_bd_CM2_PB_UART_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ESM_UART_0/zynq_bd_ESM_UART_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ESM_UART_0/zynq_bd_ESM_UART_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_ESM_UART_0/zynq_bd_ESM_UART_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_AXI_MON_0/zynq_bd_AXI_MON_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_AXI_MON_0/zynq_bd_AXI_MON_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_AXI_MON_0/zynq_bd_AXI_MON_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_INT_AXI_FW_0/zynq_bd_INT_AXI_FW_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axis_data_fifo_0_0/zynq_bd_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_0/zynq_bd_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_0/zynq_bd_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_0/zynq_bd_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_xbar_3/zynq_bd_xbar_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_0/zynq_bd_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_0/zynq_bd_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_0/zynq_bd_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_1/zynq_bd_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_1/zynq_bd_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_1/zynq_bd_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_2/zynq_bd_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_2/zynq_bd_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_auto_us_2/zynq_bd_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_1/zynq_bd_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_1/zynq_bd_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axi_dma_0_1/zynq_bd_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_axis_data_fifo_0_1/zynq_bd_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_191c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_191c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_191c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_191c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_191c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_191c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_191c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_191c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_191c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_191c_sarn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_191c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_191c_srn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_191c_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_191c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_191c_sawn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_191c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_191c_swn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_191c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_191c_sbn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_20/bd_191c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_21/bd_191c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_21/bd_191c_m00arn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_191c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_191c_m00rn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_191c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_191c_m00awn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_191c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_191c_m00wn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_191c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_191c_m00bn_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/zynq_bd_ooc.xdc]

read_ip -quiet C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/onboardclk/ip/onboardclk/onboardclk.xci
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk.xdc]
set_property used_in_implementation false [get_files -all c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/onboardclk/ip/onboardclk/onboardclk_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top.xdc
set_property used_in_implementation false [get_files C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top.xdc]

read_xdc C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top_clocks.xdc
set_property used_in_implementation false [get_files C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top_clocks.xdc]

read_xdc C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top_MGMT.xdc
set_property used_in_implementation false [get_files C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/constrs_1/imports/src/top_MGMT.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xczu7ev-fbvb900-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
