# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0.xci
# IP: The module: 'zynq_bd_SI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_SI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_SI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.srcs/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0.xci
# IP: The module: 'zynq_bd_SI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_SI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Dev/apollo_sm_vivado/apollo_sm_xu8/apollo_sm_xu8.gen/sources_1/bd/zynq_bd/ip/zynq_bd_SI_0/zynq_bd_SI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_bd_SI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
